Commit with changes (fixes #9)
mkgerasimenko/test-automatiom-testNG pull request #10
Opened 2017-11-16 13:06 UTC by mkgerasimenko

- refactored readFrom method;
 - added reflection to XmlReader class;
 - common refactoring.

2017-11-18 14:55 UTC, sskorol requested changes
@mkgerasimenko check comments please

2017-11-18 14:55 UTC, sskorol commented on src/main/java/com/waverleysoftware/data/impl/XmlReader.java
> +                .getChildren("Client"))
it's not a generic method anymore, as you've hardcoded exact entity nodes...

2017-11-18 14:55 UTC, sskorol commented on src/test/java/com/waverleysoftware/DataFromFileTest.java
> +    @Data(source = "panel.json", entity = Panel[].class)
would it work with a single entity class?

2017-11-18 14:55 UTC, sskorol commented on src/test/java/com/waverleysoftware/DataFromFileTest.java
> +    @Data(source = "clientBase.xml", entity = Client.class)
add more tests, which cover both single and multiple entities for json and xml

2017-11-19 17:32 UTC, mkgerasimenko commented
@sskorol, please, look at the changes. Thank you.

2017-11-21 14:43 UTC, mkgerasimenko commented
@sskorol, please, look at the changes. Thanks.

2017-11-21 16:20 UTC, sskorol approved these changes

2017-11-21 16:21 UTC, merged