Commit with new futures and fixes (fixes #7)
mkgerasimenko/test-automatiom-testNG pull request #8
Opened 2017-11-10 16:48 UTC by mkgerasimenko

- Created custom assertions for Client and Panel entities;
 - Created an interface Reader for reading data from a custom data source;
 - Created concrete implementations for reading data from json and xml format;
 - Created a generic utility class for data retrieval;
 - Created several tests, which read data from different external data sources;
 - Added Service Provider Interface;

2017-11-11 19:53 UTC, sskorol requested changes
@mkgerasimenko check comments please

2017-11-11 19:53 UTC, sskorol commented on build.gradle
> +            'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.9.2',
do you want to move other versions to `ext` section as well?

2017-11-11 19:53 UTC, sskorol commented on build.gradle
> +ext{
seems like a missing whitespace... do you want to reformat code?

2017-11-11 19:53 UTC, sskorol commented on build.gradle
> +        showStandardStreams = false
that's redundant if you're not using it

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/assertions/ClientAssert.java
> +        final String name = actual.getFirstName();
split methods calling with variables assignment to increase code readability...

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/assertions/ClientAssert.java
> +    public ClientAssert hasMasterCode(final int conditionForAge) {
how `masterCode` is related to `age`?

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/assertions/CustomAssertions.java
> +@SuppressWarnings("Warning")
which warning are you suppressing?

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/listemers/SecondTestListener.java
> +    public static Reader getCurrentImpl(final String dataSource) {
give it more obvious name... what does "current impl" mean in your app's context?

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/listemers/SecondTestListener.java
> +        final String extension = capitalize(dataSource.substring(dataSource.lastIndexOf('.')).replace(".", ""));
`commons-lang3` library which you are using, contains powerful string utils class, where you can get a substring after last character occurrence

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/utils/ImplLoader.java
> +public final class ImplLoader {
make it more generic... it should be a service loader for any interface you provide

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/listemers/SecondTestListener.java
> +                .filter(impl -> impl.toString().contains(extension))
there's a method called `endsWith`... you may want to use it instead...

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/listemers/SecondTestListener.java
> +                .findFirst();
you can replace previous filter with conditional `findFirst`

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/listemers/SecondTestListener.java
> +        return readerOptional.orElseGet(readerOptional::get);
no need to save result into variable if you return it on next line...

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/model/Client.java
> + * A simple model class for panel processing.
it doesn't seem like a panel

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/utils/ImplLoader.java
> +        for (Reader reader : serviceLoader) {
use streams instead

2017-11-11 19:53 UTC, sskorol commented on src/main/java/com/waverleysoftware/utils/api/Reader.java
> +public interface Reader {
give it more obvious name

2017-11-11 19:53 UTC, sskorol commented on src/test/java/com/waverleysoftware/AccessCodeTests.java
> + * A simple model class for access code testing.
it doesn't seem like a model class

2017-11-11 19:53 UTC, sskorol commented on src/test/java/com/waverleysoftware/AccessCodeTests.java
> +        final String conditionForType = "home";
it makes no sense to create a separate local variable, if you then use it on next like while assertion

2017-11-11 19:53 UTC, sskorol commented on src/test/java/com/waverleysoftware/AccessCodeTests.java
> +        SOFTASSERT.assertThat(asList(panels).get(0).getName()).as("panel name").isEqualTo("lyn");
if you're always using first element, why don't you return just a single object from data supplier?

2017-11-11 19:53 UTC, sskorol commented on src/test/java/com/waverleysoftware/BaseTest.java
> +                .forEach(System.out::println);
it's not recommended to use `sout` in production code... replace it with logger

2017-11-11 19:53 UTC, sskorol commented on src/test/java/com/waverleysoftware/DataFromFileTest.java
> +        CustomAssertions.assertThat(panel).hasPanelName("adc");
use static import to avoid class specification before method call

2017-11-14 21:49 UTC, mkgerasimenko commented
@sskorol, please look at the latest changes for this branch.

2017-11-15 07:37 UTC, sskorol requested changes
@mkgerasimenko check comments please

2017-11-15 07:37 UTC, sskorol commented on src/test/java/com/waverleysoftware/data/DataSuppliers.java
> +        final Data declaredAnnotation = method.getDeclaredAnnotation(Data.class);
you can put it into `ofNullable`

2017-11-15 07:37 UTC, sskorol commented on src/main/java/com/waverleysoftware/assertions/ClientAssert.java
> +    public ClientAssert hasNextAge(final int clientAge) {
so what does `next` mean in this context?

2017-11-15 12:58 UTC, sskorol approved these changes
LGTM

2017-11-15 12:59 UTC, merged